apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: hello-app
description: main application pipeline
serialPipeline:
 stages:
 - targetId: private-gke-autopilot
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: private-gke-autopilot
description: private gke autopilot cluster
gke:
 cluster: projects/gke-demo-347012/locations/australia-southeast1/clusters/ap-private-cluster
executionConfigs:
     - usages:
       - RENDER
       - DEPLOY
       serviceAccount: my-build-sa@gke-demo-347012.iam.gserviceaccount.com
